ELEMENTAL FUNCTION GFMMA(A, B, C, D)
  USE, INTRINSIC :: ISO_C_BINDING
  IMPLICIT NONE
  INTERFACE
     PURE FUNCTION PVN_GDET(A, B, C, D, X, T)
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: c_ptr
       IMPLICIT NONE
       REAL(KIND=BLAS_REAL_KIND), INTENT(IN) :: A, B, C, D
       TYPE(c_ptr), INTENT(IN), VALUE :: X, T
       REAL(KIND=BLAS_REAL_KIND) :: PVN_GDET
     END FUNCTION PVN_GDET
  END INTERFACE
  REAL(KIND=BLAS_REAL_KIND), INTENT(IN) :: A, B, C, D
  REAL(KIND=BLAS_REAL_KIND) :: GFMMA
  REAL(KIND=BLAS_REAL_KIND), TARGET :: X
  INTEGER(KIND=c_int), TARGET :: T
  X = -C
#ifndef NDEBUG
  T = 0_c_int
#endif
  GFMMA = PVN_GDET(A, X, D, B, C_LOC(X), C_LOC(T))
END FUNCTION GFMMA
