ELEMENTAL FUNCTION HFMA(A, B, C)
  IMPLICIT NONE
  INTERFACE
     PURE SUBROUTINE PVN_HFMA(DR, DI, AR, AI, BR, BI, CR, CI)
       IMPLICIT NONE
       REAL(KIND=BLAS_REAL_KIND), INTENT(OUT) :: DR, DI
       REAL(KIND=BLAS_REAL_KIND), INTENT(IN) :: AR, AI, BR, BI, CR, CI
     END SUBROUTINE PVN_HFMA
  END INTERFACE
  COMPLEX(KIND=BLAS_REAL_KIND), INTENT(IN) :: A, B, C
  COMPLEX(KIND=BLAS_REAL_KIND) :: HFMA
  REAL(KIND=BLAS_REAL_KIND) :: DR, DI
  CALL PVN_HFMA(DR, DI, REAL(A), AIMAG(A), REAL(B), AIMAG(B), REAL(C), AIMAG(C))
  HFMA = CMPLX(DR, DI, BLAS_REAL_KIND)
END FUNCTION HFMA
