ELEMENTAL FUNCTION HFMMA(A, B, C, D)
  IMPLICIT NONE
  INTERFACE
     PURE SUBROUTINE PVN_HFMMA(ER, EI, AR, AI, BR, BI, CR, CI, DR, DI)
       IMPLICIT NONE
       REAL(KIND=BLAS_REAL_KIND), INTENT(OUT) :: ER, EI
       REAL(KIND=BLAS_REAL_KIND), INTENT(IN) :: AR, AI, BR, BI, CR, CI, DR, DI
     END SUBROUTINE PVN_HFMMA
  END INTERFACE
  COMPLEX(KIND=BLAS_REAL_KIND), INTENT(IN) :: A, B, C, D
  COMPLEX(KIND=BLAS_REAL_KIND) :: HFMMA
  REAL(KIND=BLAS_REAL_KIND) :: ER, EI
  CALL PVN_HFMMA(ER, EI, REAL(A), AIMAG(A), REAL(B), AIMAG(B), REAL(C), AIMAG(C), REAL(D), AIMAG(D))
  HFMMA = CMPLX(ER, EI, BLAS_REAL_KIND)
END FUNCTION HFMMA
