#ifdef PVN_HMUL
ELEMENTAL FUNCTION HMUL(A, B)
  IMPLICIT NONE
  INTERFACE
     PURE SUBROUTINE PVN_HMUL(CR, CI, AR, AI, BR, BI)
       IMPLICIT NONE
       REAL(KIND=BLAS_REAL_KIND), INTENT(OUT) :: CR, CI
       REAL(KIND=BLAS_REAL_KIND), INTENT(IN) :: AR, AI, BR, BI
     END SUBROUTINE PVN_HMUL
  END INTERFACE
  COMPLEX(KIND=BLAS_REAL_KIND), INTENT(IN) :: A, B
  COMPLEX(KIND=BLAS_REAL_KIND) :: HMUL
  REAL(KIND=BLAS_REAL_KIND) :: CR, CI
  CALL PVN_HMUL(CR, CI, REAL(A), AIMAG(A), REAL(B), AIMAG(B))
  HMUL = CMPLX(CR, CI, BLAS_REAL_KIND)
END FUNCTION HMUL
#endif
