! by venovako
PURE SUBROUTINE HROTG(A, B, C, S)
  IMPLICIT NONE
#ifdef PVN_CR_MATH
#if (BLAS_REAL_KIND == 4)
  INTERFACE
     PURE FUNCTION CR_HYPOTF(X, Y) BIND(C,NAME='cr_hypotf')
       IMPLICIT NONE
       REAL(KIND=BLAS_REAL_KIND), INTENT(IN), VALUE :: X, Y
       REAL(KIND=BLAS_REAL_KIND) :: CR_HYPOTF
     END FUNCTION CR_HYPOTF
  END INTERFACE
#define HYPOT CR_HYPOTF
#elif (BLAS_REAL_KIND == 8)
  INTERFACE
     PURE FUNCTION CR_HYPOTD(X, Y) BIND(C,NAME='cr_hypot')
       IMPLICIT NONE
       REAL(KIND=BLAS_REAL_KIND), INTENT(IN), VALUE :: X, Y
       REAL(KIND=BLAS_REAL_KIND) :: CR_HYPOTD
     END FUNCTION CR_HYPOTD
  END INTERFACE
#define HYPOT CR_HYPOTD
#elif (BLAS_REAL_KIND == 10)
  INTERFACE
     PURE FUNCTION CR_HYPOTL(X, Y) BIND(C,NAME='cr_hypotl')
       IMPLICIT NONE
       REAL(KIND=BLAS_REAL_KIND), INTENT(IN), VALUE :: X, Y
       REAL(KIND=BLAS_REAL_KIND) :: CR_HYPOTL
     END FUNCTION CR_HYPOTL
  END INTERFACE
#define HYPOT CR_HYPOTL
#elif (BLAS_REAL_KIND == 16)
  INTERFACE
     PURE FUNCTION CR_HYPOTQ(X, Y) BIND(C,NAME='cr_hypotq')
       IMPLICIT NONE
       REAL(KIND=BLAS_REAL_KIND), INTENT(IN), VALUE :: X, Y
       REAL(KIND=BLAS_REAL_KIND) :: CR_HYPOTQ
     END FUNCTION CR_HYPOTQ
  END INTERFACE
#define HYPOT CR_HYPOTQ
#else
#error CR_HYPOT not defined
#endif
#endif
#ifdef HMUL
  INTERFACE
     ELEMENTAL FUNCTION HMUL(A, B)
       IMPLICIT NONE
       COMPLEX(KIND=BLAS_REAL_KIND), INTENT(IN) :: A, B
       COMPLEX(KIND=BLAS_REAL_KIND) :: HMUL
     END FUNCTION HMUL
  END INTERFACE
#else
#define HMUL(A,B) ((A)*(B))
#endif
  COMPLEX(KIND=BLAS_REAL_KIND), INTENT(INOUT) :: A
  COMPLEX(KIND=BLAS_REAL_KIND), INTENT(IN) :: B
  REAL(KIND=BLAS_REAL_KIND), INTENT(OUT) :: C
  COMPLEX(KIND=BLAS_REAL_KIND), INTENT(OUT) :: S
  REAL(KIND=BLAS_REAL_KIND), PARAMETER :: ZERO = 0.0, HALF = 0.5, ONE = 1.0
  REAL(KIND=BLAS_REAL_KIND) :: AR, AI, BR, BI, MA, MB, M
  C = ONE
  S = CMPLX(ZERO, ZERO, BLAS_REAL_KIND)
  AR = REAL(A)
  AI = AIMAG(A)
  IF (.NOT. (ABS(AR) .LE. HUGE(AR))) RETURN
  IF (.NOT. (ABS(AI) .LE. HUGE(AI))) RETURN
  BR = REAL(B)
  BI = -AIMAG(B)
  IF ((AR .EQ. ZERO) .AND. (AI .EQ. ZERO) .AND. ((.NOT. (BR .EQ. ZERO)) .OR. (.NOT. (BI .EQ. ZERO)))) THEN
     C = ZERO
     S = CMPLX(ONE, ZERO, BLAS_REAL_KIND)
     A = B
     RETURN
  END IF
  IF (.NOT. (ABS(BR) .LE. HUGE(BR))) RETURN
  IF (.NOT. (ABS(BI) .LE. HUGE(BI))) RETURN
1 IF (AR .EQ. ZERO) THEN
     MA = ABS(AI)
  ELSE IF (AI .EQ. ZERO) THEN
     MA = ABS(AR)
  ELSE ! A complex
     MA = HYPOT(AR, AI)
  END IF
  IF (.NOT. (MA .LE. HUGE(MA))) GOTO 2
  IF (BR .EQ. ZERO) THEN
     MB = ABS(BI)
  ELSE IF (BI .EQ. ZERO) THEN
     MB = ABS(BR)
  ELSE ! B complex
     MB = HYPOT(BR, BI)
  END IF
  IF (.NOT. (MB .LE. HUGE(MB))) GOTO 2
  IF (MA .EQ. ZERO) THEN
     M = MB
  ELSE IF (MB .EQ. ZERO) THEN
     M = MA
  ELSE ! MA*MB > 0
     M = HYPOT(MA, MB)
  END IF
  IF (.NOT. (M .LE. HUGE(M))) GOTO 2
  IF (MA .EQ. ZERO) THEN
     AR = ONE
     AI = ZERO
     C = ZERO
     S = CMPLX(BR / M, BI / M, BLAS_REAL_KIND)
     A = CMPLX(M, ZERO, BLAS_REAL_KIND)
  ELSE ! MA > 0
     AR = AR / MA
     AI = AI / MA
     C = MA / M
     S = HMUL(CMPLX(AR, AI, BLAS_REAL_KIND), CMPLX(BR / M, BI / M, BLAS_REAL_KIND))
     A = CMPLX(AR * M, AI * M, BLAS_REAL_KIND)
  END IF
  RETURN
2 AR = AR * HALF
  AI = AI * HALF
  BR = BR * HALF
  BI = BI * HALF
  GOTO 1
END SUBROUTINE HROTG
