PROGRAM THROTG
  IMPLICIT NONE
  INTERFACE
     PURE SUBROUTINE HROTG(A, B, C, S)
       IMPLICIT NONE
       COMPLEX(KIND=BLAS_REAL_KIND), INTENT(INOUT) :: A
       COMPLEX(KIND=BLAS_REAL_KIND), INTENT(IN) :: B
       REAL(KIND=BLAS_REAL_KIND), INTENT(OUT) :: C
       COMPLEX(KIND=BLAS_REAL_KIND), INTENT(OUT) :: S
     END SUBROUTINE HROTG
  END INTERFACE
  REAL(KIND=BLAS_REAL_KIND), PARAMETER :: ZERO = 0.0, ONE = 1.0, MXN = HUGE(MXN)
  INTEGER, PARAMETER :: NAB = 14
  COMPLEX(KIND=BLAS_REAL_KIND), PARAMETER :: AB(2,NAB) = RESHAPE((/&
       CMPLX(ZERO,ZERO,BLAS_REAL_KIND), CMPLX(ZERO,ZERO,BLAS_REAL_KIND),&
       CMPLX( ONE,ZERO,BLAS_REAL_KIND), CMPLX(ZERO,ZERO,BLAS_REAL_KIND),&
       CMPLX(ZERO,ZERO,BLAS_REAL_KIND), CMPLX( ONE,ZERO,BLAS_REAL_KIND),&
       CMPLX( ONE,ZERO,BLAS_REAL_KIND), CMPLX( ONE,ZERO,BLAS_REAL_KIND),&
       CMPLX(-ONE,ZERO,BLAS_REAL_KIND), CMPLX(ZERO,ZERO,BLAS_REAL_KIND),&
       CMPLX(ZERO,ZERO,BLAS_REAL_KIND), CMPLX(-ONE,ZERO,BLAS_REAL_KIND),&
       CMPLX(-ONE,ZERO,BLAS_REAL_KIND), CMPLX( ONE,ZERO,BLAS_REAL_KIND),&
       CMPLX( ONE,ZERO,BLAS_REAL_KIND), CMPLX(-ONE,ZERO,BLAS_REAL_KIND),&
       CMPLX(-ONE,ZERO,BLAS_REAL_KIND), CMPLX(-ONE,ZERO,BLAS_REAL_KIND),&
       CMPLX( MXN,ZERO,BLAS_REAL_KIND), CMPLX( ONE,ZERO,BLAS_REAL_KIND),&
       CMPLX( ONE,ZERO,BLAS_REAL_KIND), CMPLX( MXN,ZERO,BLAS_REAL_KIND),&
       CMPLX( MXN,ZERO,BLAS_REAL_KIND), CMPLX(ZERO, MXN,BLAS_REAL_KIND),&
       CMPLX(ZERO, MXN,BLAS_REAL_KIND), CMPLX( MXN,ZERO,BLAS_REAL_KIND),&
       CMPLX( MXN, MXN,BLAS_REAL_KIND), CMPLX( MXN, MXN,BLAS_REAL_KIND) &
       /), (/2,NAB/))
  COMPLEX(KIND=BLAS_REAL_KIND) :: A, B, S
  REAL(KIND=BLAS_REAL_KIND) :: C
  INTEGER :: I
  DO I = 1, NAB
     A = AB(1,I)
     B = AB(2,I)
     WRITE (*,'(A,2(ES18.9E4,A))') 'A=(', REAL(A), ',', AIMAG(A), ')'
     WRITE (*,'(A,2(ES18.9E4,A))') 'B=(', REAL(B), ',', AIMAG(B), ')'
     CALL HROTG(A, B, C, S)
     WRITE (*,'(A,2(ES18.9E4,A))') 'R=(', REAL(A), ',', AIMAG(A), ')'
     WRITE (*,'(A,2(ES18.9E4,A))') 'S=(', REAL(S), ',', AIMAG(S), ')'
     WRITE (*,'(A,ES18.9E4)') 'C=', C
  END DO
END PROGRAM THROTG
