PROGRAM THROTG
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INPUT_UNIT, OUTPUT_UNIT
  IMPLICIT NONE
  INTERFACE
     PURE SUBROUTINE HROTG(A, B, C, S)
       IMPLICIT NONE
       COMPLEX(KIND=BLAS_REAL_KIND), INTENT(INOUT) :: A
       COMPLEX(KIND=BLAS_REAL_KIND), INTENT(IN) :: B
       REAL(KIND=BLAS_REAL_KIND), INTENT(OUT) :: C
       COMPLEX(KIND=BLAS_REAL_KIND), INTENT(OUT) :: S
     END SUBROUTINE HROTG
  END INTERFACE
  REAL(KIND=BLAS_REAL_KIND) :: AR, AI, BR, BI, C
  COMPLEX(KIND=BLAS_REAL_KIND) :: A, B, S
  WRITE (OUTPUT_UNIT,'(A)',ADVANCE='NO') 'Re(A) = '
  READ (INPUT_UNIT,*) AR
  WRITE (OUTPUT_UNIT,'(A)',ADVANCE='NO') 'Im(A) = '
  READ (INPUT_UNIT,*) AI
  A = CMPLX(AR, AI, BLAS_REAL_KIND)
  WRITE (OUTPUT_UNIT,'(A)',ADVANCE='NO') 'Re(B) = '
  READ (INPUT_UNIT,*) BR
  WRITE (OUTPUT_UNIT,'(A)',ADVANCE='NO') 'Im(B) = '
  READ (INPUT_UNIT,*) BI
  B = CMPLX(BR, BI, BLAS_REAL_KIND)
  CALL HROTG(A, B, C, S)
  WRITE (OUTPUT_UNIT,'(A,ES17.9)') 'Re(R) = ', REAL(A)
  WRITE (OUTPUT_UNIT,'(A,ES17.9)') 'Im(R) = ', AIMAG(A)
  WRITE (OUTPUT_UNIT,'(A,ES17.9)') '    C = ', C
  WRITE (OUTPUT_UNIT,'(A,ES17.9)') 'Re(S) = ', REAL(S)
  WRITE (OUTPUT_UNIT,'(A,ES17.9)') 'Im(S) = ', AIMAG(S)
END PROGRAM THROTG
