! by venovako
PROGRAM TIHMAX2
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: OUTPUT_UNIT
  IMPLICIT NONE
#ifdef PVN_CR_MATH
#if (BLAS_REAL_KIND == 4)
  INTERFACE
     PURE FUNCTION CR_HYPOTF(X, Y) BIND(C,NAME='cr_hypotf')
       IMPLICIT NONE
       REAL(KIND=BLAS_REAL_KIND), INTENT(IN), VALUE :: X, Y
       REAL(KIND=BLAS_REAL_KIND) :: CR_HYPOTF
     END FUNCTION CR_HYPOTF
  END INTERFACE
#define HYPOT CR_HYPOTF
#elif (BLAS_REAL_KIND == 8)
  INTERFACE
     PURE FUNCTION CR_HYPOTD(X, Y) BIND(C,NAME='cr_hypot')
       IMPLICIT NONE
       REAL(KIND=BLAS_REAL_KIND), INTENT(IN), VALUE :: X, Y
       REAL(KIND=BLAS_REAL_KIND) :: CR_HYPOTD
     END FUNCTION CR_HYPOTD
  END INTERFACE
#define HYPOT CR_HYPOTD
#elif (BLAS_REAL_KIND == 10)
  INTERFACE
     PURE FUNCTION CR_HYPOTL(X, Y) BIND(C,NAME='cr_hypotl')
       IMPLICIT NONE
       REAL(KIND=BLAS_REAL_KIND), INTENT(IN), VALUE :: X, Y
       REAL(KIND=BLAS_REAL_KIND) :: CR_HYPOTL
     END FUNCTION CR_HYPOTL
  END INTERFACE
#define HYPOT CR_HYPOTL
#elif (BLAS_REAL_KIND == 16)
#if (HAVE_FMA == 15)
#warning IEEE quad not yet available
#else
  INTERFACE
     PURE FUNCTION CR_HYPOTQ(X, Y) BIND(C,NAME='cr_hypotq')
       IMPLICIT NONE
       REAL(KIND=BLAS_REAL_KIND), INTENT(IN), VALUE :: X, Y
       REAL(KIND=BLAS_REAL_KIND) :: CR_HYPOTQ
     END FUNCTION CR_HYPOTQ
  END INTERFACE
#define HYPOT CR_HYPOTQ
#endif
#else
#error CR_HYPOT not defined
#endif
#endif
  INTEGER, PARAMETER :: M = 2 * 3 * 5, N = M / 2
  INTEGER, EXTERNAL :: IHAMAX, IHMAX2
  REAL(KIND=BLAS_REAL_KIND) :: X(M)
  INTEGER :: I, J
  CALL RANDOM_NUMBER(X)
  J = 1
  DO I = 1, M, 2
     WRITE (OUTPUT_UNIT,'(I2,4(A,ES16.9))') J, ':(', X(I), ',', X(I+1), ');', (ABS(X(I)) + ABS(X(I+1))), ',', HYPOT(X(I), X(I+1))
     J = J + 1
  END DO
  WRITE (OUTPUT_UNIT,'(A,I2)') 'IHAMAX=', IHAMAX(N, X, 1)
  WRITE (OUTPUT_UNIT,'(A,I2)') 'IHMAX2=', IHMAX2(N, X, 1)
END PROGRAM TIHMAX2
