PROGRAM TXERBLA
  IMPLICIT NONE
  INTERFACE
     PURE SUBROUTINE XERBLA(SRNAME, INFO)
       IMPLICIT NONE
       CHARACTER(LEN=*), INTENT(IN) :: SRNAME
       INTEGER, INTENT(IN) :: INFO
     END SUBROUTINE XERBLA
  END INTERFACE
  INTERFACE
     PURE FUNCTION PVN_GET_ERRNO()
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT32
       IMPLICIT NONE
       INTEGER(KIND=INT32) :: PVN_GET_ERRNO
     END FUNCTION PVN_GET_ERRNO
  END INTERFACE
  INTEGER :: E
  E = 1
  CALL XERBLA('XERBLA', E)
  E = INT(PVN_GET_ERRNO())
  PRINT *, E
END PROGRAM TXERBLA
