PROGRAM TXERBLA
  IMPLICIT NONE
  INTERFACE
     PURE SUBROUTINE XERBLA(SRNAME, INFO)
       IMPLICIT NONE
       CHARACTER(LEN=*), INTENT(IN) :: SRNAME
       INTEGER, INTENT(IN) :: INFO
     END SUBROUTINE XERBLA
  END INTERFACE
  INTERFACE
     PURE FUNCTION XERRNO()
       IMPLICIT NONE
       INTEGER :: XERRNO
     END FUNCTION XERRNO
  END INTERFACE
  INTEGER :: E
  E = 1
  CALL XERBLA('XERBLA', E)
  E = XERRNO()
  PRINT *, E
END PROGRAM TXERBLA
