PURE FUNCTION XERRNO()
  IMPLICIT NONE
  INTERFACE
     PURE FUNCTION PVN_GET_ERRNO()
       USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT32
       IMPLICIT NONE
       INTEGER(KIND=INT32) :: PVN_GET_ERRNO
     END FUNCTION PVN_GET_ERRNO
  END INTERFACE
  INTEGER :: XERRNO
  XERRNO = INT(PVN_GET_ERRNO())
END FUNCTION XERRNO
